export declare const eas: {
    en: {
        '#docusaurus_skipToContent_fallback > button': string;
        '.menu__link--active': string;
        ".menu__link[href*='/purpose']": string;
        ".menu__link[href*='/quick-start']": string;
        ".menu__link[href*='/core-concepts']": string;
        ".menu__link[href*='/developer-tools']": string;
        ".menu__link[href*='/tutorials']": string;
        ".menu__link[href*='/the-explorer']": string;
        ".menu__link[href*='/ideas-to-build']": string;
        '.navbar__title': string;
        ".navbar__link[href*='easscan.org']": string;
        ".navbar__link[href*='attest.sh']": string;
        ".navbar__link[href*='github.com/ethereum-attestation-service']": string;
        ".breadcrumbs__link[aria-label='Home page']": string;
        '.breadcrumbs__item--active > span': string;
        h1: string;
        'article p:nth-of-type(1)': string;
        'article p:nth-of-type(2)': string;
        'article p:nth-of-type(3) > a:nth-of-type(1)': string;
        'article p:nth-of-type(3) > a:nth-of-type(2)': string;
        'article p:nth-of-type(4) strong': string;
        'article p:nth-of-type(5)': string;
        'article p:nth-of-type(6)': string;
        'article p:nth-of-type(7) strong': string;
        'article p:nth-of-type(8) strong': string;
        'article p:nth-of-type(8)': string;
        'article p:nth-of-type(9) strong': string;
        'article p:nth-of-type(9)': string;
        'article p:nth-of-type(10) strong': string;
        'article p:nth-of-type(10)': string;
        'article p:nth-of-type(11) strong': string;
        'article p:nth-of-type(11)': string;
        'article p:nth-of-type(12) strong': string;
        'article p:nth-of-type(12)': string;
        'article p:nth-of-type(13)': string;
        'article p:nth-of-type(14) strong': string;
        'article p:nth-of-type(14)': string;
        'article p:nth-of-type(15)': string;
        'article p:nth-of-type(16)': string;
        'article p:nth-of-type(17)': string;
        'article p:nth-of-type(18)': string;
        'article p:nth-of-type(19)': string;
        'article p:nth-of-type(20) strong': string;
        'article p:nth-of-type(20)': string;
        'article p:nth-of-type(21)': string;
        'article p:nth-of-type(22)': string;
        'article p:nth-of-type(23)': string;
    };
    zh_TW: {
        '#docusaurus_skipToContent_fallback > button': string;
        '.menu__link--active': string;
        ".menu__link[href*='/purpose']": string;
        ".menu__link[href*='/quick-start']": string;
        ".menu__link[href*='/core-concepts']": string;
        ".menu__link[href*='/developer-tools']": string;
        ".menu__link[href*='/tutorials']": string;
        ".menu__link[href*='/the-explorer']": string;
        ".menu__link[href*='/ideas-to-build']": string;
        '.navbar__title': string;
        ".navbar__link[href*='easscan.org']": string;
        ".navbar__link[href*='attest.sh']": string;
        ".navbar__link[href*='github.com/ethereum-attestation-service']": string;
        ".breadcrumbs__link[aria-label='Home page']": string;
        '.breadcrumbs__item--active > span': string;
        h1: string;
        'article p:nth-of-type(1)': string;
        'article p:nth-of-type(2)': string;
        'article p:nth-of-type(3) > a:nth-of-type(1)': string;
        'article p:nth-of-type(3) > a:nth-of-type(2)': string;
        'article p:nth-of-type(4) strong': string;
        'article p:nth-of-type(5)': string;
        'article p:nth-of-type(6)': string;
        'article p:nth-of-type(7) strong': string;
        'article p:nth-of-type(8) strong': string;
        'article p:nth-of-type(8)': string;
        'article p:nth-of-type(9) strong': string;
        'article p:nth-of-type(9)': string;
        'article p:nth-of-type(10) strong': string;
        'article p:nth-of-type(10)': string;
        'article p:nth-of-type(11) strong': string;
        'article p:nth-of-type(11)': string;
        'article p:nth-of-type(12) strong': string;
        'article p:nth-of-type(12)': string;
        'article p:nth-of-type(13)': string;
        'article p:nth-of-type(14) strong': string;
        'article p:nth-of-type(14)': string;
        'article p:nth-of-type(15)': string;
        'article p:nth-of-type(16)': string;
        'article p:nth-of-type(17)': string;
        'article p:nth-of-type(18)': string;
        'article p:nth-of-type(19)': string;
        'article p:nth-of-type(20) strong': string;
        'article p:nth-of-type(20)': string;
        'article p:nth-of-type(21)': string;
        'article p:nth-of-type(22)': string;
        'article p:nth-of-type(23)': string;
    };
};
//# sourceMappingURL=sites-data.fixture.d.ts.map